language: node_js
node_js:
  - 14

services:
  - docker

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - aws --version
  - aws configure set aws_access_key_id $AWS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws configure list

install:
  - echo "no install"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t ton-sales-api:$TRAVIS_BUILD_NUMBER .
  - docker tag ton-sales-api:$TRAVIS_BUILD_NUMBER 477539478664.dkr.ecr.sa-east-1.amazonaws.com/ton-sales-api:$TRAVIS_BUILD_NUMBER

after_success:
  - echo "aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 477539478664.dkr.ecr.sa-east-1.amazonaws.com"
  - docker push 477539478664.dkr.ecr.sa-east-1.amazonaws.com/ton-sales-api:$TRAVIS_BUILD_NUMBER
