language: node_js
node_js:
  - 14

services:
  - docker

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli

install:
  - echo "[default]
aws_access_key_id = $AWS_KEY_ID
aws_secret_access_key = $AWS_SECRET_KEY" >> ~/.aws/config

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t ton-sales-api:$TRAVIS_BUILD_NUMBER .
  - docker tag ton-sales-api:$TRAVIS_BUILD_NUMBER $ECR_REPOSITORY_URL/ton-sales-api:$TRAVIS_BUILD_NUMBER

after_success:
  # - echo "docker login --username AWS --password $ECR_TOKEN $ECR_REPOSITORY_URL"
  - echo "aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL"
  - docker push $ECR_REPOSITORY_URL/ton-sales-api:$TRAVIS_BUILD_NUMBER
